sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: GREAT Project
description: Helping families move toward employment and training
url: http://www.yesproject.org
baseurl: 
email: info@yesproject.org
github: 
copyright: "The YES Project is funded by Big Lottery Fund and the European Social Fund. The service is managed by Voluntary Action LeicesterShire (VAL).</p><p><a href=\"http://www.valonline.org.uk\">Voluntary Action LeicesterShire</a> is the trading name of Voluntary Action Leicester registered charity (No. 509300) Registered in England and Wales. Copyright © 2016 Voluntary Action Leicester"

#  Social media settings

facebook: "yourprojectyes"
permalink: pretty

# Services

analyticstracking: "UA-84927932-1"

# Pagination

paginate: 5
paginate_path: "/news/:num/"

#  Timezone
timezone: Europe/London

exclude: ['bower.json']
exclude: ['grunt']

# Conditional Stylesheets

conditionalstylesheets:
  - target: "ie9"
    path: "/css/ie9.css"

#  Configuration for prose.io online editor
prose:
  ignore: 
    - '_includes'
    - 'assets'
    - '_assets'
    - '_layouts'
    - '_plugins'
    - '/.jekyll-metadata'
    - 'feed.xml'
    - 'js'
    - 'css'
    - '_sass'
    - 'CNAME'
    - '.bowerrc'
    - '.gitignore'
    - '404.md'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'README.md'
    - '_config.yml'
    - 'bower.json'
    - 'favicon.ico'
  media: img
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: false
      - name: "summary"
        field:
          label: "Summary"
          element: "textarea"
          value: null
      - name: "thumbnail-image"
        field:
          label: "Thumbnail Image"
          element: "text"
          placeholder: "/img/thumbnails/case-study-thumbnail.jpg"
          value: "/img/thumbnails/case-study-thumbnail.jpg"
      - name: "layout"
        field:
          label: "Layout"
          element: "select"
          value: "default"
          options:
            - name: 'Default'
              value: 'default'
            - name: 'No Sidebars'
              value: 'no-sidebars'
      - name: "category"
        field:
          label: "Category"
          element: "select"
          value: "default"
          options:
            - name: 'Coalville & Greenhill'
              value: 'coalville-greenhill'
            - name: 'Loughborough'
              value: 'loughborough'
            - name: 'Measham'
              value: 'measham'
            - name: 'Wigston'
              value: 'wigston'