sass:
  style: compressed

#  Build settings
markdown: kramdown

gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
   
#  Site settings
title: YES Project
description: Supporting you to take steps towards finding work
url: https://www.yesproject.org
baseurl: 
email: info@yesproject.org
github: 
copyright: "The YES Project is funded by Big Lottery Fund and the European Social Fund. The service is managed by Voluntary Action LeicesterShire (VAL).</p><p><a href=\"http://www.valonline.org.uk\">Voluntary Action LeicesterShire</a> is the trading name of Voluntary Action Leicester registered charity (No. 509300) Registered in England and Wales. Copyright © 2016 Voluntary Action Leicester"

#  Social media settings

facebook: "yourprojectyes"
permalink: pretty

# Services

analyticstracking: "UA-84927932-1"

# Pagination

paginate: 9
paginate_path: "/news/:num/"

#  Timezone

timezone: Europe/London

exclude:
  - bower.json
  - grunt

# Conditional Stylesheets

conditionalstylesheets:
  - target: "ie9"
    path: "/css/ie9.css"

# Events configuration

collections:
  events:
    output: true
    permalink: /events/:path/

# Configuration for prose.io online editor

prose:
  media: img
  ignore: 
    - '_includes'
    - 'assets'
    - '_assets'
    - '_layouts'
    - '_plugins'
    - '/.jekyll-metadata'
    - 'feed.xml'
    - 'js'
    - 'css'
    - '_sass'
    - 'CNAME'
    - '.bowerrc'
    - '.gitignore'
    - '404.md'
    - 'news.xml'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'license.md'
    - 'README.md'
    - '_config.yml'
    - 'bower.json'
    - 'favicon.ico'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          label: "Date"
          element: "text"
          value: CURRENT_DATETIME
      - name: "summary"
        field:
          label: "Summary"
          element: "textarea"
          value: null
      - name: "thumbnail-image"
        field:
          label: "Thumbnail Image"
          element: "text"
          placeholder: "/img/placeholder-thumbnail.png"
          value: "/img/placeholder.jpg"
      - name: "layout"
        field:
          label: "Layout"
          element: "select"
          value: "post"
          options:
            - name: 'Blog post'
              value: 'post'
            - name: 'Default'
              value: 'default'
            - name: 'Course'
              value: 'course'
            - name: 'No Sidebars'
              value: 'no-sidebars'
    _events:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "summary"
        field:
          label: "Summary"
          element: "textarea"
          value: null
      - name: "day"
        field:
          element: "number"
          label: "Day"
          value: 1
      - name: "month"
        field:
          element: "select"
          value: "01"
          label: "Month"
          options:
            - name: 'January'
              value: '01'
            - name: 'February'
              value: '02'
            - name: 'March'
              value: '03'
            - name: 'April'
              value: '04'
            - name: 'May'
              value: '05'
            - name: 'June'
              value: '06'
            - name: 'July'
              value: '07'
            - name: 'August'
              value: '08'
            - name: 'September'
              value: '09'
            - name: 'October'
              value: '10'
            - name: 'November'
              value: '11'
            - name: 'December'
              value: '12'
      - name: "year"
        field:
          element: "select"
          value: "2016"
          label: "Year"
          options:
            - name: '2016'
              value: '2016'
            - name: '2017'
              value: '2017'
            - name: '2018'
              value: '2018'